[tools]
ripgrep = "latest"
terraform-ls = "latest"
awscli = "latest"
python = "system"
opentofu = "latest"
usage = "latest"
go = "latest"
terraform = "latest"
direnv = "latest"
pre-commit = "latest"
jq = "latest"
mc = "2023-08-29T22-55-06Z"
poetry = "latest"
yq = "latest"
nodejs = "21.2.0"
helm = "3.13.3"
kubectx = "0.9.5"
flux2 = "2.2.2"
sops = "3.8.1"
age = "latest"
qdns = "latest"
k9s = "0.31.7"
cilium-cli = "0.13.2"
cilium-hubble = "0.12.0"
calicoctl = "3.27.0"
kind = "0.22.0"
ruby = "3.2.1"
eza = "0.18.5"
bat = "0.24.0"
marp-cli = "3.4.0"
terragrunt = "0.54.22"
terraform-docs = "latest"
clusterctl = "1.6.3"
gojq = "latest"
jqp = "0.5.0"
shellcheck = "latest"
zoxide = "latest"
github-cli = "latest"
delta = "latest"
chezmoi = "latest"
fzf = "latest"
tflint = "latest"
kubectl = "latest"
fd = "latest"
yarn = "latest"
