[settings]
python_compile = false
experimental = true
lockfile = true
idiomatic_version_file_enable_tools = ["node"]

[tools]
ripgrep = "latest"
terraform-ls = "latest"
opentofu = "latest"
usage = "latest"
go = "latest"
direnv = "latest"
pre-commit = "latest"
jq = "latest"
yq = "latest"
helm = "latest"
kubectx = "latest"
flux2 = "latest"
sops = "latest"
qdns = "0.19.2"
k9s = "latest"
cilium-cli = "latest"
cilium-hubble = "latest"
kind = "latest"
eza = "latest"
bat = "latest"
marp-cli = "latest"
terraform-docs = "latest"
gojq = "latest"
jqp = "latest"
shellcheck = "latest"
zoxide = "latest"
github-cli = "latest"
delta = "latest"
chezmoi = "latest"
fzf = "latest"
tflint = "latest"
kubectl = "latest"
fd = "latest"
node = "latest"
pandoc = "latest"
"aqua:kubecolor/kubecolor" = "latest"
dive = "latest"
helmfile = "latest"
trivy = "latest"
crane = "latest"
talosctl = "latest"
ruff = "latest"
"github:dlvhdr/diffnav" = "latest"
"github:kubetail-org/kubetail" = "latest"
goreleaser = "latest"
starship = "latest"
shfmt = "latest"
slsa-verifier = "latest"
krew = "latest"
terragrunt = "latest"
vcluster = "latest"
golangci-lint = "latest"
"go:github.com/magefile/mage" = "latest"
"go:golang.org/x/tools/cmd/goimports" = "latest"
kustomize = "latest"
"github:stackitcloud/stackit-cli" = "latest"
"go:github.com/spf13/cobra-cli" = "latest"
kube-controller-tools = "latest"
kubebuilder = "latest"
