[settings]
python_compile = false
lockfile = true
idiomatic_version_file_enable_tools = ["node"]

[tools]
ripgrep = "latest"
terraform-ls = "latest"
opentofu = "latest"
usage = "latest"
go = "latest"
direnv = "latest"
pre-commit = "latest"
jq = "latest"
yq = "latest"
helm = "latest"
flux2 = "latest"
sops = "latest"
age = "latest"
qdns = "0.19.2"
k9s = "latest"
cilium-cli = "latest"
cilium-hubble = "latest"
kind = "latest"
eza = "latest"
bat = "latest"
marp-cli = "latest"
terragrunt = "latest"
terraform-docs = "latest"
clusterctl = "latest"
gojq = "latest"
jqp = "latest"
shellcheck = "latest"
zoxide = "latest"
github-cli = "latest"
delta = "latest"
chezmoi = "latest"
fzf = "latest"
tflint = "latest"
kubectl = "latest"
fd = "latest"
node = "latest"
pandoc = "latest"
"aqua:kubecolor/kubecolor" = "latest"
dive = "latest"
helmfile = "latest"
trivy = "latest"
crane = "latest"
talosctl = "latest"
ruff = "latest"
cosign = "latest"
"github:kubetail-org/kubetail" = "latest"
goreleaser = "latest"
starship = "latest"
shfmt= "latest"
slsa-verifier = "latest"
krew = "latest"
"ubi:danielfoehrKn/kubeswitch" = "latest"
bitwarden = "latest"
"github:controlplaneio-fluxcd/flux-operator" = { version = "latest", asset_pattern = "flux-operator_*_linux_*" }
